#define components and theirs paths to detect changes
lcm-bricks:
  - 'VERSION'
  - '.github/containers/lcm-bricks.env'
lcm-bricks-nextversion:
  - 'VERSION'
  - '.github/containers/lcm-bricks-nextversion.env'
