AbcSize:
  Enabled: false

ClassLength:
  Enabled: false

ModuleLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

EachWithObject:
  Enabled: false
  
Eval:
  Enabled: false

FormatString:
  Enabled: false

HashSyntax:
  Enabled: false

LineLength:
  Max: 323

MethodLength:
  Enabled: false

PerceivedComplexity:
  Enabled: false

Alias:
  Enabled: false

Casecmp:
  Enabled: false

ConditionalAssignment:
  Enabled: false

GuardClause:
  Enabled: false

IdenticalConditionalBranches:
  Enabled: false

IfInsideElse:
  Enabled: false

IneffectiveAccessModifier:
  Enabled: false

MultilineMethodCallIndentation:
  Enabled: false

MutableConstant:
  Enabled: false

RedundantBlockCall:
  Enabled: false

RedundantMerge:
  Enabled: false

RedundantParentheses:
  Enabled: false

StringLiterals:
  Enabled: false

SignalException:
  Enabled: false

TimesMap:
  Enabled: false

UnneededDisable:
  Enabled: false

UnneededInterpolation:
  Enabled: false

UselessAccessModifier:
  Enabled: false
