AbcSize:
  Enabled: false

ClassLength:
  Enabled: false

ModuleLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

EachWithObject:
  Enabled: false
  
Eval:
  Enabled: false

FormatString:
  Enabled: false

HashSyntax:
  Enabled: false

LineLength:
  Max: 323

MethodLength:
  Enabled: false

PerceivedComplexity:
  Enabled: false
