name: LCM Integration E2E Pipeline

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
      ruby_version:
        required: true
        type: string

env:
  RT_S3_BUCKET_NAME: "gdc-dev-eu-integration-tests"
  JAVA_HOME: /usr/lib/jvm/java-${{ inputs.java_version }}-openjdk-amd64
  PATH: /usr/lib/jvm/java-${{ inputs.java_version }}-openjdk-amd64/bin:/usr/local/bin:/usr/bin:/bin

jobs:
  LCM-integration-e2e-tests:
    runs-on:
      group: infra1-runners-arc
      labels: runners-rxa-xlarge
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.TOKEN_GITHUB_YENKINS }}
      - name: Set up JRuby + Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby_version }}
          bundler-cache: true
      - name: Build image
        run: |
          bundle exec rake -f lcm.rake docker:build
      - name: Build gems
        run: |
          bundle exec rake -f lcm.rake docker:bundle
      - name: Run integrated tests
        run: |
          bundle exec rake -f lcm.rake test:docker:integration-e2e
        env:
          GD_SPEC_PASSWORD: ${{ secrets.RUBY_TEST_PASSWORD }}
          RT_S3_BUCKET_NAME: ${{ env.RT_S3_BUCKET_NAME }}
          RT_S3_ACCESS_KEY: ${{ secrets.RUBY_TEST_S3_ACCESS_KEY }}
          RT_S3_SECRET_KEY: ${{ secrets.RUBY_TEST_S3_SECRET_KEY }}
          GD_DEV_DEV_TOKEN: ${{ secrets.RUBY_TEST_DEV_TOKEN }}
          GD_DEV_PROD_TOKEN: ${{ secrets.RUBY_TEST_PROD_TOKEN }}
          GD_DEV_VERTICA_DEV_TOKEN: ${{ secrets.RUBY_TEST_DEV_TOKEN_VERTICA }}
          GD_DEV_VERTICA_PROD_TOKEN: ${{ secrets.RUBY_TEST_PROD_TOKEN_VERTICA }}
          GD_DEV_PASSWORD: ${{ secrets.RUBY_TEST_PASSWORD }}
          GD_DEV_DEFAULT_PASSWORD: ${{ secrets.RUBY_TEST_PASSWORD }}
          GD_TEST_DEV_TOKEN: ${{ secrets.RUBY_TEST_DEV_TOKEN }}
          GD_TEST_PROD_TOKEN: ${{ secrets.RUBY_TEST_PROD_TOKEN }}
          GD_TEST_VERTICA_DEV_TOKEN: ${{ secrets.RUBY_TEST_DEV_TOKEN_VERTICA }}
          GD_TEST_VERTICA_PROD_TOKEN: ${{ secrets.RUBY_TEST_PROD_TOKEN_VERTICA }}
          GD_TEST_PASSWORD: ${{ secrets.RUBY_TEST_PASSWORD }}
          GD_TEST_DEFAULT_PASSWORD: ${{ secrets.RUBY_TEST_PASSWORD }}
          GD_STG_DEV_TOKEN: ${{ secrets.RUBY_TEST_DEV_TOKEN }}
          GD_STG_PROD_TOKEN: ${{ secrets.RUBY_TEST_PROD_TOKEN }}
          GD_STG_VERTICA_DEV_TOKEN: ${{ secrets.RUBY_TEST_DEV_TOKEN_VERTICA }}
          GD_STG_VERTICA_PROD_TOKEN: ${{ secrets.RUBY_TEST_PROD_TOKEN_VERTICA }}
          GD_STG_PASSWORD: ${{ secrets.RUBY_TEST_PASSWORD }}
          GD_STG_DEFAULT_PASSWORD: ${{ secrets.RUBY_TEST_PASSWORD }}

